language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: db09bbe3-c0c6-41cb-8047-f1e88f42e92c
  app: warm-oasis-85595
  on:
    repo: FranciaMoran/react-hot-cold-test
cache:
  directories:
    - node_modules
env:
  - CI=true